{% set name = "skyrim" %}
{% set version = "0.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/skyrim-{{ version }}.tar.gz
  sha256: 53d1a19b9ddd6a1aef69812b092d392fc09cd735a2220ded245d46a8735cae35

build:
  entry_points:
    - forecast = skyrim.forecast:main
  noarch: python
  script:
    - sed -i.bak "s/s3fs==0.4.2/s3fs>=0.4.2/g" pyproject.toml
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.10
    - setuptools
    - setuptools-scm
    - pip
  run:
    - python >=3.10
    - modal
    - loguru
    - xarray
    - base58
    - botocore
    - aiobotocore
    - boto3
    - s3fs >=0.4.2
    - zarr
    - scipy
    - pandas
    - click
    - earth2mip 0.1.*

test:
  imports:
    - skyrim
  commands:
    - pip check
    - forecast --help
  requires:
    - pip

about:
  home: https://github.com/secondlaw-ai/skyrim
  summary: AI weather models united.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - isuruf
    - timkpaine
